# Generated by Django 3.2.8 on 2022-03-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='img',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgLNLbFmOl-wuybKGc6IrdKYGPxe62xr-wYA&usqp=CAU', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
